name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'feature'
  - title: 'ğŸ› Hotfixes'
    label: 'bug'
  - title: 'ETC'
    label: 'documentation'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Uncategorized
  $CHANGES